<?php

// TODO share with .install. Watch vocabulary / term stuff.
// TODO run coder.
// TODO look for dpm / todos.
// TODO document functions

/**
 * Get a list of breadcrumb types, keyed by their associated table.
 */
function _custom_breadcrumbs_features_get_types() {
  return array(
    'custom_breadcrumb'                      => array('name' => t('Custom Breadcrumbs Node'),       'module' => 'custom_breadcrumb'),
    'custom_breadcrumbsapi'                  => array('name' => t('Custom Breadcrumbs Api'),        'module' => 'custom_breadcrumbsapi'),
    'custom_breadcrumbs_panels'              => array('name' => t('Custom Breadcrumbs Panels'),     'module' => 'custom_breadcrumbs_panel'),
    'custom_breadcrumbs_paths'               => array('name' => t('Custom Breadcrumbs Paths'),      'module' => 'custom_breadcrumbs_paths'),
    'custom_breadcrumbs_taxonomy_term'       => array('name' => t('Custom Breadcrumbs Term'),       'module' => 'custom_breadcrumbs_taxonomy'),
    'custom_breadcrumbs_taxonomy_vocabulary' => array('name' => t('Custom Breadcrumbs Vocabulary'), 'module' => 'custom_breadcrumbs_taxonomy'),
    'custom_breadcrumbs_views'               => array('name' => t('Custom Breadcrumbs Views'),      'module' => 'custom_breadcrumbs_views'),
  );
}

/**
 * Implements hook_features_api().
 */
function custom_breadcrumbs_features_features_api() {
  $cb_types = _custom_breadcrumbs_features_get_types();
  $exports = array();
  foreach ($cb_types as $table => $cb_type) {
    $exports[$table] = array(
      'name' => $cb_type['name'],
      'feature_source' => TRUE,
      'default_hook' => $table . '_features_default_settings',
      'file' => drupal_get_path('module', 'custom_breadcrumbs_features') . '/custom_breadcrumbs_features.features.inc',
    );
  }
  return $exports;
}


/**
 * Implements hook_form_alter().
 * TODO js fill name
 */
function custom_breadcrumbs_features_form_alter(&$form, &$form_alter, $form_id) {
  switch ($form_id) {
    case 'custom_breadcrumbs_form':
    case 'custom_breadcrumbsapi_form':
    case 'custom_breadcrumbs_panels_form':
    case 'custom_breadcrumbs_paths_form':
    case 'custom_breadcrumbs_taxonomy_term_form':
    case 'custom_breadcrumbs_taxonomy_vocabulary_form':
    case 'custom_breadcrumbs_views_form':
      $form['name']['#required'] = TRUE;
      $form['name']['#attached']['js'] = array(
        drupal_get_path('module', 'custom_breadcrumbs_features') . '/js/custom_breadcrumbs_features.js',
      );
      $form['machine_name'] = array(
        '#type' => 'machine_name',
        '#default_value' => '', // TODO set current machine name (if exists).
        '#maxlength' => 32,
        '#disabled' => FALSE, // TODO set TRUE if already set.
        '#machine_name' => array(
          'exists' => 'custom_breadcrumbs_features_load',
        ),
        '#description' => t('A unique machine-readable name for this breadcrumb. It must only contain lowercase letters, numbers, and underscores. This name will be used when featurizing breadcrumbs.'),
        '#weight' => -49,
      );
  }
}

/**
 * Loads a breadcrumb.
 * TODO we may re-use a function from custom_breadcrumbs.module
 */
function custom_breadcrumbs_features_load($stuff) { // TODO change stuff
  dpm($stuff);
  return FALSE;
}

// TODO move features.inc in includes/
