<?php

// TODO share with .install. Watch vocabulary / term stuff.
// TODO run coder.
// TODO look for dpm / todos.
// TODO document functions

/**
 * Get a list of breadcrumb types, keyed by their associated table.
 */
function _custom_breadcrumbs_features_get_types() {
  return array(
    'custom_breadcrumb'             => array('name' => t('Custom Breadcrumbs Node'),       'module' => 'custom_breadcrumb'),
    'custom_breadcrumbsapi'         => array('name' => t('Custom Breadcrumbs Api'),        'module' => 'custom_breadcrumbsapi'),
    'custom_breadcrumbs_panels'     => array('name' => t('Custom Breadcrumbs Panels'),     'module' => 'custom_breadcrumbs_panel'),
    'custom_breadcrumbs_paths'      => array('name' => t('Custom Breadcrumbs Paths'),      'module' => 'custom_breadcrumbs_paths'),
    'custom_breadcrumbs_term'       => array('name' => t('Custom Breadcrumbs Term'),       'module' => 'custom_breadcrumbs_taxonomy'),
    'custom_breadcrumbs_views'      => array('name' => t('Custom Breadcrumbs Views'),      'module' => 'custom_breadcrumbs_views'),
    'custom_breadcrumbs_vocabulary' => array('name' => t('Custom Breadcrumbs Vocabulary'), 'module' => 'custom_breadcrumbs_taxonomy'),
  );
}

/**
 * Implements hook_features_api().
 */
function custom_breadcrumbs_features_features_api() {
  $types = _custom_breadcrumbs_features_get_types();
  $exports = array();
  foreach ($exportables as $table => $type) {
    $exports[$table] = array(
      'name' => $type['name'],
      'feature_source' => TRUE,
      'default_hook' => $table . '_features_default_settings',
      'file' => drupal_get_path('module', 'custom_breadcrumbs_features') . '/custom_breadcrumbs_features.features.inc',
    );
  }
  return $export;
}

